name: efficient_intrinsic_gridview
description:
  This widget calculates intrinsic max size (or mainAxisExtend) of every crossAxis item on a GridView. 
  So you are not stuck with just one mainAxisExtend.
  And it does that very efficiently, only rendering the element that is being displayed to the user,
  without using expensive IntrinsicHeight or IntrinsicWidth widget

repository: https://github.com/AradhyaNepal/efficient_intrinsic_gridview
issue_tracker: https://github.com/AradhyaNepal/efficient_intrinsic_gridview/issues
version: 0.0.3-unstable-release

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

